doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: false
            horizon:
                url: '%env(resolve:HORIZON_DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
    orm:
        auto_generate_proxy_classes: true
        controller_resolver:
            auto_mapping: true
        enable_lazy_ghost_objects: true
        entity_managers:
            default:
                report_fields_where_declared: true
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

            horizon:
                report_fields_where_declared: true
                validate_xml_mapping: true
                connection: horizon
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Horizon:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Horizon'
                        prefix: 'App\Entity\Horizon'
                        alias: Horizon

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
