twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        globalValues: '@App\Service\GlobalValueService'

when@test:
    twig:
        strict_variables: true
